# ./docker-compose.yml

version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: customers_db
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
    ports:
      - "9906:3306"
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html/
      - ./site.conf:/etc/nginx/sites-available/default
      - ./site.conf:/etc/nginx/sites-enabled/default
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
      - db
  php:
    image: php:7-fpm
    restart: always
    volumes:
      - ./:/var/www/html


#  web:
#    image: php:7.2.2-apache
#    container_name: php_web
#    depends_on:
#      - db
#    volumes:
#      - ./:/var/www/html/
#      - ./site.conf:/etc/nginx/conf.d/site.conf
#    ports:
#      - "8100:80"
#    stdin_open: true
#    tty: true

  composer:
    image: "composer"
    command: install
    volumes:
      - ./:/app





